### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by jiaming-jx** [billyriantono/s2cellid-node#2]
```
> node-gyp rebuild

make: Entering directory '/home/laskuma/Pokemon-GO-node-api/node_modules/s2geometry-node/build'
  CXX(target) Release/obj.target/NativeExtension/src/NativeExtension.o
In file included from ../geometry/util/math/mathutil.h:22:0,
                 from ../geometry/util/math/vector3-inl.h:40,
                 from ../geometry/s2.h:19,
                 from ../src/point.h:7,
                 from ../src/NativeExtension.cc:2:
../geometry/util/math/mathlimits.h: In static member function ‘static bool MathLimits<float>::IsFinite(MathLimits<float>::Type)’:
../geometry/util/math/mathlimits.h:194:55: error: ‘isinf’ was not declared in this scope
   static bool IsFinite(const Type x) { return !isinf(x)  &&  !isnan(x); } \
```

node -v v6.3.0
npm -v 3.10.3

**Comment by billyriantono** [comment]
what is you gcc version ?

**Comment by jiaming-jx** [comment]
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1)

**Comment by billyriantono** [comment]
let me check first,because mine is tested in v4.x

**Comment by billyriantono** [comment]
try using gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4 i can compiled with that version until i can updated to support v 5.x @LASkuma

**Comment by jiaming-jx** [comment]
```
laskuma@ubuntu:~/Pokemon-GO-node-api$ CC=/usr/bin/gcc-4.8&&CXX=/usr/bin/g++-4.8 npm install

> s2geometry-node@1.1.4 install /home/laskuma/Pokemon-GO-node-api/node_modules/s2geometry-node
> node-gyp rebuild

make: Entering directory '/home/laskuma/Pokemon-GO-node-api/node_modules/s2geometry-node/build'
  CXX(target) Release/obj.target/NativeExtension/src/NativeExtension.o
In file included from ../geometry/util/math/mathutil.h:22:0,
                 from ../geometry/util/math/vector3-inl.h:40,
                 from ../geometry/s2.h:19,
                 from ../src/point.h:7,
                 from ../src/NativeExtension.cc:2:
../geometry/util/math/mathlimits.h: In static member function ‘static bool MathLimits<float>::IsFinite(MathLimits<float>::Type)’:
../geometry/util/math/mathlimits.h:194:55: error: ‘isinf’ was not declared in this scope
   static bool IsFinite(const Type x) { return !isinf(x)  &&  !isnan(x); } \
                                                       ^
../geometry/util/math/mathlimits.h:226:3: note: in expansion of macro ‘DECL_FP_LIMIT_FUNCS’
   DECL_FP_LIMIT_FUNCS \
   ^
../geometry/util/math/mathlimits.h:229:1: note: in expansion of macro ‘DECL_FP_LIMITS’
 DECL_FP_LIMITS(float, FLT)
 ^
../geometry/util/math/mathlimits.h:194:55: note: suggested alternative:
   static bool IsFinite(const Type x) { return !isinf(x)  &&  !isnan(x); } \
                                                       ^
../geometry/util/math/mathlimits.h:226:3: note: in expansion of macro ‘DECL_FP_LIMIT_FUNCS’
   DECL_FP_LIMIT_FUNCS \
   ^
../geometry/util/math/mathlimits.h:229:1: note: in expansion of macro ‘DECL_FP_LIMITS’
 DECL_FP_LIMITS(float, FLT)
 ^
In file included from /usr/include/c++/4.8/random:38:0,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from ../../nan/nan.h:50,
                 from ../src/point.h:6,
                 from ../src/NativeExtension.cc:2:
/usr/include/c++/4.8/cmath:614:5: note:   ‘std::isinf’
     isinf(_Tp __x)

```

Still no luck. Cannot pass build with gcc-4.8 and g++-4.8.

**Comment by jiaming-jx** [comment]
Find some reference here https://github.com/rethinkdb/rethinkdb/issues/5450
Solution: https://github.com/rethinkdb/rethinkdb/commit/84be09f314c4cbf88b4ac8fe9dbff1d36f0f5781

I can try to get my hands on that.

**Comment by billyriantono** [comment]
okay thanks i will updated it soon .. Thanks

**Comment by jiaming-jx** [comment]
I tried the method above. It would compile but will fail the test. Still trying to figure out why.

**Comment by jiaming-jx** [comment]
I was using Ubuntu 16.04. Now I've just switched into Ubuntu 14.04 and everything works fine ATM. Maybe it's a compatibility issue with that specific version of Ubuntu.

**Comment by billyriantono** [comment]
@LASkuma  you are test using npm test ? i am not yet update the test script it will be failed overall 👍
